# Generated by Django 4.1.3 on 2022-12-26 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_city_ticket_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='start_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Start time'),
        ),
    ]
