# Generated by Django 4.1.3 on 2022-12-26 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_ticket_start_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='TicketPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('person_type', models.CharField(choices=[('STUDENT', 'STUDENT'), ('CHILD', 'CHILD'), ('PENSIONER', 'PENSIONER'), ('ADULT', 'ADULT')], default='ADULT', max_length=255)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Price')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='price',
        ),
        migrations.AddField(
            model_name='ticket',
            name='price',
            field=models.ManyToManyField(related_name='tickets', to='api.ticketprice', verbose_name='Prices'),
        ),
    ]
