# Generated by Django 4.1.3 on 2022-12-26 17:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_ticketprice_remove_ticket_price_ticket_price'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ticketprice',
            options={'verbose_name': 'Price', 'verbose_name_plural': 'Prices'},
        ),
    ]
