# Generated by Django 4.1.3 on 2022-12-26 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_ticketprice_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='images',
            field=models.ManyToManyField(null=True, related_name='tickets', to='api.image', verbose_name='Images'),
        ),
    ]
